"""
--- Day 10: The Stars Align ---

It's no use; your navigation system simply isn't capable of providing walking
directions in the arctic circle, and certainly not in 1018.

The Elves suggest an alternative. In times like these, North Pole rescue
operations will arrange points of light in the sky to guide missing Elves back
to base. Unfortunately, the message is easy to miss: the points move slowly
enough that it takes hours to align them, but have so much momentum that they
only stay aligned for a second. If you blink at the wrong time, it might be
hours before another message appears.

You can see these points of light floating in the distance, and record their
position in the sky and their velocity, the relative change in position per
second (your puzzle input). The coordinates are all given from your
perspective; given enough time, those positions and velocities will move the
points into a cohesive message!

Rather than wait, you decide to fast-forward the process and calculate what the
points will eventually spell.

For example, suppose you note the following points:

position=< 9,  1> velocity=< 0,  2>
position=< 7,  0> velocity=<-1,  0>
position=< 3, -2> velocity=<-1,  1>
position=< 6, 10> velocity=<-2, -1>
position=< 2, -4> velocity=< 2,  2>
position=<-6, 10> velocity=< 2, -2>
position=< 1,  8> velocity=< 1, -1>
position=< 1,  7> velocity=< 1,  0>
position=<-3, 11> velocity=< 1, -2>
position=< 7,  6> velocity=<-1, -1>
position=<-2,  3> velocity=< 1,  0>
position=<-4,  3> velocity=< 2,  0>
position=<10, -3> velocity=<-1,  1>
position=< 5, 11> velocity=< 1, -2>
position=< 4,  7> velocity=< 0, -1>
position=< 8, -2> velocity=< 0,  1>
position=<15,  0> velocity=<-2,  0>
position=< 1,  6> velocity=< 1,  0>
position=< 8,  9> velocity=< 0, -1>
position=< 3,  3> velocity=<-1,  1>
position=< 0,  5> velocity=< 0, -1>
position=<-2,  2> velocity=< 2,  0>
position=< 5, -2> velocity=< 1,  2>
position=< 1,  4> velocity=< 2,  1>
position=<-2,  7> velocity=< 2, -2>
position=< 3,  6> velocity=<-1, -1>
position=< 5,  0> velocity=< 1,  0>
position=<-6,  0> velocity=< 2,  0>
position=< 5,  9> velocity=< 1, -2>
position=<14,  7> velocity=<-2,  0>
position=<-3,  6> velocity=< 2, -1>

Each line represents one point. Positions are given as <X, Y> pairs: X
represents how far left (negative) or right (positive) the point appears,
while Y represents how far up (negative) or down (positive) the point appears.

At 0 seconds, each point has the position given. Each second, each point's
velocity is added to its position. So, a point with velocity <1, -2> is moving
to the right, but is moving upward twice as quickly. If this point's initial
position were <3, 9>, after 3 seconds, its position would become <6, 3>.

Over time, the points listed above would move like this:

Initially:
........#.............
................#.....
.........#.#..#.......
......................
#..........#.#.......#
...............#......
....#.................
..#.#....#............
.......#..............
......#...............
...#...#.#...#........
....#..#..#.........#.
.......#..............
...........#..#.......
#...........#.........
...#.......#..........

After 1 second:
......................
......................
..........#....#......
........#.....#.......
..#.........#......#..
......................
......#...............
....##.........#......
......#.#.............
.....##.##..#.........
........#.#...........
........#...#.....#...
..#...........#.......
....#.....#.#.........
......................
......................

After 2 seconds:
......................
......................
......................
..............#.......
....#..#...####..#....
......................
........#....#........
......#.#.............
.......#...#..........
.......#..#..#.#......
....#....#.#..........
.....#...#...##.#.....
........#.............
......................
......................
......................

After 3 seconds:
......................
......................
......................
......................
......#...#..###......
......#...#...#.......
......#...#...#.......
......#####...#.......
......#...#...#.......
......#...#...#.......
......#...#...#.......
......#...#..###......
......................
......................
......................
......................

After 4 seconds:
......................
......................
......................
............#.........
........##...#.#......
......#.....#..#......
.....#..##.##.#.......
.......##.#....#......
...........#....#.....
..............#.......
....#......#...#......
.....#.....##.........
...............#......
...............#......
......................
......................

After 3 seconds, the message appeared briefly: HI. Of course, your message will
be much longer and will take many more seconds to appear.

What message will eventually appear in the sky?
"""
import itertools
from typing import List, Tuple


def read_input(
    filename: str
    ) -> Tuple[List[Tuple[int, int]], List[Tuple[int, int]]]:

    position = []
    velocity = []

    with open(filename) as f:
        for line in f:
            splitted = line.strip().lstrip('position=<').rstrip('>').split(',')
            mid = splitted[1].split('> velocity=<')
            px = int(splitted[0])
            py = int(mid[0])
            vx = int(mid[-1])
            vy = int(splitted[-1])
            position.append((px, py))
            velocity.append((vx, vy))

    return position, velocity


def draw_message(
    t: int,
    position: List[Tuple[int, int]],
    velocity: List[Tuple[int, int]]
    ) -> None:

    result = []
    for (y0, x0), (dy, dx) in zip(position, velocity):
        x, y = x0 + dx * t, y0 + dy * t
        result.append((x, y))

    result.sort(key=lambda x: x[0])

    min_height = min(x for x, y in result)
    max_height = max(x for x, y in result)

    min_width = min(y for x, y in result)
    max_width = max(y for x, y in result)

    grid = [[' '] * (max_width - min_width + 1) for _ in range(max_height - min_height + 1)]

    for x, y in result:
        grid[x - min_height][y - min_width] = '#'

    for row in grid:
        print(''.join(row))


def find_min(
    position: List[Tuple[int, int]],
    velocity: List[Tuple[int, int]]
    ) -> int:

    result = []

    for t in range(20000):

        min_height = min(x + t * vx for (y, x), (vy, vx) in zip(position, velocity))
        max_height = max(x + t * vx for (y, x), (vy, vx) in zip(position, velocity))
    
        min_width = min(y + t * vy for (y, x), (vy, vx) in zip(position, velocity))
        max_width = max(y + t * vy for (y, x), (vy, vx) in zip(position, velocity))

        result.append(max_width - min_width + max_height - min_height)

    return result.index(min(result))


if __name__ == "__main__":

    pos, vel = read_input('test.txt')
    t = find_min(pos, vel)
    pos, vel = read_input('test.txt')
    print(f"After {t} seconds:")
    draw_message(t, pos, vel)

    pos, vel = read_input('input.txt')
    t = find_min(pos, vel)
    pos, vel = read_input('input.txt')
    print(f"After {t} seconds:")
    draw_message(t, pos, vel)
